const ENVIRONMENT = {
	TYPE: ['testnet', 'betanet'],
	SERVERS: {
		testnet: {
			SERVER_URL: 'http://testnet-02.quantachain.io:7000',
		},
		betanet: {},
	},
	HORIZON_SERVER: 'http://testnet-02.quantachain.io:8000',
};

const SETTINGS = {
	ACCOUNT_TRIM_LENGTH: 4,
	RECENT_ITEM_LENGTH: 8,
	ASSET_TYPE_NATIVE: 'QDEX',
	QUANTA_ISSUER: 'QBJUMEXBXBQN6NGHVGE4U3IWLYKF6RZ2JXY67CBSLKPXNZPLJ2KZ5DWH',
	QUANTA_ORDERBOOK: 'QCAO4HRMJDGFPUHRCLCSWARQTJXY2XTAFQUIRG2FAR3SCF26KQLAWZRN',
	ACCOUT_START_WITH: 'Q',
};

module.exports = {
	SETTINGS,
	ENVIRONMENT,
};
